spring:
    application:
        name: api-gateway
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: management-service
                  uri: lb://management-service
                  predicates:
                      - Path=/api/v1/management/**
                      - Path=/management-service/swagger-ui/**, /management-service/swagger-resources/**, /management-service/v3/api-docs/**
                  filters:
                      - RewritePath=/api/v1/management/?(?<segment>.*), /$\{segment}
                      - RewritePath=/management-service/swagger-ui/?(?<segment>.*), /swagger-ui/$\{segment}
                      - RewritePath=/management-service/swagger-resources/?(?<segment>.*), /swagger-resources/$\{segment}
                      - RewritePath=/management-service/v3/api-docs/?(?<segment>.*), /v3/api-docs/$\{segment}
                - id: ai-assistant
                  uri: lb://ai-assistant
                  predicates:
                      - Path=/api/v1/ai/**
                      - Path=/ai-service/swagger-ui/**, /ai-service/swagger-resources/**, /ai-service/v3/api-docs/**
                  filters:
                      - RewritePath=/api/v1/ai/?(?<segment>.*), /$\{segment}
                      - RewritePath=/ai-service/swagger-ui/?(?<segment>.*), /swagger-ui/$\{segment}
                      - RewritePath=/ai-service/swagger-resources/?(?<segment>.*), /swagger-resources/$\{segment}
                      - RewritePath=/ai-service/v3/api-docs/?(?<segment>.*), /v3/api-docs/$\{segment}
                - id: payment-service
                  uri: lb://payment-service
                  predicates:
                      - Path=/api/v1/payment/**
                      - Path=/payment-service/swagger-ui/**, /payment-service/swagger-resources/**, /payment-service/v3/api-docs/**
                  filters:
                      - RewritePath=/api/v1/payment/?(?<segment>.*), /$\{segment}
                      - RewritePath=/payment-service/swagger-ui/?(?<segment>.*), /swagger-ui/$\{segment}
                      - RewritePath=/payment-service/swagger-resources/?(?<segment>.*), /swagger-resources/$\{segment}
                      - RewritePath=/payment-service/v3/api-docs/?(?<segment>.*), /v3/api-docs/$\{segment}
                - id: knowledge-base
                  uri: lb://knowledge-base
                  predicates:
                      - Path=/api/v1/knowledge-base/**
                      - Path=/knowledge-base/swagger-ui/**, /knowledge-base/swagger-resources/**, /knowledge-base/v3/api-docs/**
                  filters:
                      - RewritePath=/api/v1/knowledge-base/?(?<segment>.*), /$\{segment}
                      - RewritePath=/knowledge-base/swagger-ui/?(?<segment>.*), /swagger-ui/$\{segment}
                      - RewritePath=/knowledge-base/swagger-resources/?(?<segment>.*), /swagger-resources/$\{segment}
                      - RewritePath=/knowledge-base/v3/api-docs/?(?<segment>.*), /v3/api-docs/$\{segment}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/

keycloak:
    url: http://localhost:9999
    admin: admin
    password: 1234
    secret: Ge9Hg14J0fajXyQnHRCWlU0gNsCcih4t
    client: car-service
    get-token-url: '${keycloak.url}/realms/car-service-realm/protocol/openid-connect/token'
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui/index.html
        urls:
            - url: /v3/api-docs
              name: API Gateway Service
            - url: /management-service/v3/api-docs
              name: Management Service
            - url: /payment-service/v3/api-docs
              name: Payment Service
            - url: /ai-service/v3/api-docs
              name: AI Service
            - url: /knowledge-base/v3/api-docs
              name: Knowledge Base Service
logging.level.root: INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
logging.level.org.springframework.cloud.gateway: DEBUG
